post9p.go

Mount9p is untested. I can't find it.

Fix 9pfuse mount using -m flag

---

fsys_test.go

This should enable tests to run in Travis CI. A fake devdraw can be used later when we have it.
Update #64

Use Xvfb for testing if $DISPLAY is not set

---

frame/frame.go
frame/unlockedproxy.go

Help with #52 by improving TextOccupiedHeight with a rectangle
argument.

Enhance TextOccupiedHeight for column layout

---

exec.go
look.go

Replace some %r format specifier with Go error

---

frame/ptofchar.go
frame/ptofchar_test.go

This is more faithful to the C code.

[Frame] Don't panic when selecting an invalid rune

---

.travis.yml

In d309a18, Fazlul made go vet pass. Get the builder to try to keep
it that way.

Force vet checking

---

wind.go

Show window is dirty even if text is cached

---

acme.go
exec.go

Show running commands in the row tag

---

ecmd.go
edit.go
look.go
look_test.go

Also fix Edit D command parsing, and fix and test dirname function.
Helps #53

Implement Edit D command

---

exec.go

Writes were being buffered in the pipe created in fsopenfd.
Wait can return before the pipes are cleared
(e.g. exit status may be printed before all of stderr is printed).
Instead, remove the pipe and pass fid directly to exec.Cmd.

Don't terminate command before it's done writing

---

ecmd.go

Commit 29ecd19 undid some changes from previous commit.

Fix Edit D command after bad merge

---

acme.go
dat.go
exec.go

Local command is not very useful outside of Plan 9, but it exercises
some untested code.

Implement Local command

---

fsys_test.go

Xvfb sometimes didn't start up within 3 seconds.

Use xdpyinfo to wait for Xvfb to start up

---

ecmd.go
file.go

Also enable Undo for filename in tag.

Implement Edit e command

---

acme.go
ecmd.go
edit.go
exec.go
file.go
look.go
row.go
text.go
util.go
wind.go
xfid.go

Window.dirty is actually an attribute of File. Remove Window.dirty and
instead ask the backing File object for its dirty state.

Remove Window.dirty

---

README.md

Hopefully show that continuous builder is operating correctly. Helps #146

Update README.md: revised builder

---

rune.go
wind.go

Fix crash when the entire tag is deleted

---

file.go
file_test.go

This was just a mistransliteration of the C code.
Fixes #149

Don't crash when deleting a zerox

---

addr.go
addr_test.go

Also add more tests and simplify some code.

Fix evaluation of addresses with semicolon

---

edit.go
edit_test.go

Also make it return error. The plan is to eventually have all the
parsing functions return error, making them easier to test.

Test simple address parsing

---

edit.go
edit_test.go
fsys.go

- use fmt.Errorf instead of errors.New to match existing code
- move Addr.String() method to edit_test.go
until we have some test for it

Test compound address parsing

---

acme.go
ecmd.go
edit.go
exec.go
file.go
file_test.go
internal/file/file_hash.go
look.go
row.go
text.go
wind.go
xfid.go

Further code cleanup, remove another use of File.text.

Remove another use of File.text

---

.travis.yml
exec_test.go
fsys_test.go
go.mod
go.sum
internal/complete/complete_test.go
look_test.go

* I'm skipping all the tests that are failing on Windows for now.
* Added Go 1.12.
Helps #116

Test Windows and macOS build in Travis

---

.travis.yml
README.md
acme_p9p.go
fsys_p9p.go
fsys_unix.go
go.mod
go.sum

* Also create plan9port namespace directory if it doesn't exist.

Make plan9port optional with 'duitdraw mux9p' tags

---

internal/frame/select.go

internal/frame: clip sp1 selection bound if out of range

---

dat.go
fsys.go
fsys_test.go

As discussed here: https://github.com/rjkroege/edwood/pull/218

Use a map for MntDir collection instead of linked list

---

ecmd.go
edit.go
edit_test.go

Add additional editcmd tests. In particular, test sam commands e and
r. Fix bug #191 in e_cmd demonstrated by the added tests.

More editcmd tests

---

ecmd.go
edit_test.go

Add unit tests for a number of additional Edit commands.

Increase test coverage of Edit commands

---

file.go
wind.go
wind_test.go

Fix crash when snarfing empty selection using mouse chord

---

col.go
ecmd.go
edit_test.go

Further increase editcmd unit test coverage.

Add more editcmd tests

---

edit_test.go

Extend test coverage of Edit commands. Test B and start of testing w.

Add more Edit command tests

---

edit_test.go
rowmock_test.go

Add a test for the sam u (and its redo variant.) Also add a handy
utility to add text to a Window in the row/column/window mock.

Add a test for sam u command

---

col.go
exec_test.go
file.go
file_test.go
row_test.go
text_test.go
wind.go

misspell: https://github.com/client9/misspell

Fix spelling mistakes found by misspell

---

xfid.go
xfid_test.go

We were crashing if we were trying to read less than 4 (`utf8.UTFMax`)
runes. The function also didn't handle muti-byte characters correctly
and it returned the number of bytes read instead of the number of runes.
I've changed the function to be more similar to the C code, decoding
runes from the beginning of the bytes buffer instead of try to find the
rune boundary from the end of the buffer. Finding the boundary doesn't
solve the problem of computing the number of runes, which we need to
return.
Fixes #255

Fix xfidruneread for small reads and multi-byte characters

---

dat.go
xfid.go
xfid_test.go

Document xfidruneread and add xfidread test for QWxdata

---

disk.go
disk_test.go
fsys.go
look.go

Also, remove some debugging prints in `newx`.

Clean up temporary file used in Disk test

---

look.go

The `9fans.net/go/plumb` package caches the connection (`*client.Fsys`)
to the plumber. So, if the plumber isn't running when Edwood starts up, we
will never gain a connection to the plumber, even if the plumber is
started. Similarly, we never regain connection after losing it. The fix
manually connects to the plumber using `client.MountService`.
Also fix some missed `Fid.Close`: plumbsendfid and plumbeditfid wasn't
being closed in some branches.

Fix reconnection to plumber

---

text.go
text_test.go

Fixes #297
/CC @danieljamespost

Fix crash when typing tab in row or column tags

---

testacme.sh

Added "-p" arg to mkdir to fix the "file already exists" warning

---

go.mod
go.sum

Use mux9p version. Fixes #314.

Rev mux9p version

---

acme.go
acme_test.go
addr_test.go
bufferobserver.go
col.go
ecmd.go
ecmd_test.go
edit.go
edit_test.go
exec.go
exec_test.go
file.go
file_test.go
internal/file/diskdetails.go
logf.go
look.go
look_test.go
observableeditablebuffer.go
row.go
rowmock_test.go
rune_array.go
text.go
text_test.go
wind.go
wind_test.go
xfid.go
xfid_test.go

Added the interface for observer and the various refactorings required to make it work with the existing code. #334 #97

Observer interface

---

acme.go
acme_test.go
addr_test.go
col.go
dat.go
ecmd.go
ecmd_test.go
edit.go
exec.go
exec_test.go
internal/file/buffer_observer.go
internal/file/file.go
internal/file/file_test.go
internal/file/observable_editable_buffer.go
internal/file/rune_array.go
internal/file/rune_array_test.go
internal/util/util.go
look.go
look_test.go
row.go
rowmock_test.go
text.go
text_test.go
util.go
util_test.go
wind.go
wind_test.go
xfid.go
xfid_test.go

Isolated the components of the new file out into internal/file as a step towards the new undo.Buffer #334 
Not dependent on any other branch.

Moved files needed for new File to internal/file

---

internal/file/diskdetails.go
internal/file/file.go
internal/file/observable_editable_buffer.go

Moved isdir to DiskDetails to further move functionality out of file.

Moved isdir from file to DiskDetails

---

internal/file/file.go
internal/file/observable_editable_buffer.go

Moved SetName from file to OEB to further move functionality from file to OEB for adding undo.

Moved SetName from file to OEB

---

undo/LICENSE
undo/undo.go
undo/undo_test.go

Added the new undo buffer along with it's tests. #334

Added undo.Buffer

---

addr_test.go
exec_test.go
file/observable_editable_buffer.go
look_test.go
text_test.go
wind_test.go
xfid_test.go

Removed RuneArray from the constructor of OEB as well as calls to it to move towards the underlying byte array model #334

No more rune array

---

exec_test.go

Start of test of exec.go:/cut/.

more exec tests

---

xfid_test.go

At some point, I failed to update all of the Xfid test to setup
correct test pre-conditions and accidentally got all of them working
by virtue of side-effects on the global object. Fixed.

Fix xfd tests for isolated execution

---

acme.go
edit.go
exec.go
look.go
row.go
util.go
wind.go
xfid.go

- Observer-driven tag updates
- Remove SetTag

tagupdate simplifications

---

edit_test.go
file/observable_editable_buffer.go
wind.go

Fix #317: X* D commands on mutated buffers didn't succeed on the
second attempt.

Fix issue 317

---

frame/insert_more_test.go
frame/insert_test.go

Further increase test coverage on frame.Insert. Helps with #56. Added
width equality match tests.

Increase frame.Insert test coverage

---

file/offset_tuple.go
file/offset_tuple_test.go

Add file.BufferCursor: an implementation of io.RuneReader using a
backing file.Buffer.

Add a file.BufferCursor

---

file/buffer.go
file/file_test.go
file/helpers_test.go
file/observable_editable_buffer.go
text.go

- Removed some dead code
- Removed unnecessary Commit concept

codecleanups 1

---

frame/testing_helpers_test.go

In a previous commit, I merged an incomplete test. Oops. Suppress this
test until I've fixed it.

Suppress a failing test

---

cmd/win/win.go

Turn off debugging and turn it on with -d flag.

win: add debug flag
