rjkroege/edwood

- exec.go
To reproduce, select spaces and middle click on it.
```
$ edwood
Untested: main.run(0x0, 0xc42026af34, 0x3, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...): .../exec.go:674 +0x34
panic: runtime error: index out of range
goroutine 50 [running]:
main.runproc(0x0, 0xc42026af34, 0x3, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
.../exec.go:975 +0x11f2
created by main.run
.../exec.go:686 +0x148
```
> Fix crash when executing empty command

- .gitignore
- acme.go
- fsys_test.go
"focus" can show up before "new" in the log,
for the same window id
> Make fsys log test more lenient

- ecmd.go
- edit.go
The plan9port acme calls threadexits inside editerror, so we should call
runtime.Goexit. We could instead add a return immediate after each
call to editerror, but this seems easier (and safer).
Fixes #67
> Make sure editthread goroutine terminates on error

- util.go
- xfid.go
- xfid_test.go
Edwood was putting null characters in the window when writing non-ascii
characters to cons file.
The code is now aligned with plan9port acme.
> Handle unicode correctly on writes to cons

- fsys_test.go
- xfid.go
Most of the diffs in `fsys_test.go` are whitespace changes. View the diff with `-b` flag if needed.
> Fix reads from body for large files

- exec.go
- text.go
- xfid.go
Edwood child processes forked to run |command were lingering and
not closing the Acme filesystem connection back to the parent Edwood
until (sometimes) significantly later. When the child xfidclose-ed
the wrsel file, it would change the parent's selection back to what
it was when command was first middle-clicked. This caused issue
soon as command completes. It also reverts part of ffe7178 now that
the underlying cause of seeing the panic (asynchronous selection
mutation) has been fixed.
> Shutdown connections from forked children

- acme.go
- buf.go
- fsys_test.go
- look.go
- xfid.go
These are all the calls to cvttorunes in acme that are relevant in
edwood. It doesn't include indirect calls from helper function
bytetorune, which doesn't exist in Edwood.
Fixes #54 and similar issues.
> Eliminate more null characters

- go.mod
- go.sum
The next Go release (go1.11) will have experimental support for modules.
Update #35
> Add Go module support

- exec.go
- text.go
- wind.go
Remove redundant fields ncache and ncachealloc since they are just len
and cap of the slice.
> Simplify Text cache

- addr.go
- col.go
- dat.go
- ecmd.go
- edit.go
- exec.go
- frame/delete.go
- frame/draw.go
- frame/insert.go
- frame/ptofchar.go
- frame/tick.go
- fsys.go
- logf.go
- look.go
- text.go
- wind.go
- xfid.go
This change is *most* automated. grind was used to perform some
cleanup on go's compiler when it was first migrated from C. Most
notably, it moves variable declaration closer to use.
After applying grind, I used uncovert to remove some unnecessary type casts.
> run rsc.io/grind on edwood

- fsys.go
- xfid.go
It's not portable, and you generally don't have to worry about the
close-on-exec flag -- Go will take care of it. See comment at the top of
https://golang.org/src/syscall/exec_unix.go for more details.
> Remove calls to syscall.CloseOnExec

- dat.go
- text.go
- util.go
Also remove unused Dirlist struct (we use 2 slices instead of []Dirlist).
Fixes #113
> Fix crash when listing filenames with non-ascii characters

- fsys.go
- post9p.go
- util.go
Also make acmeerror panic. This prevents a nil pointer dereference in
fsysproc() -- the code assumes acmeerror exits the program.
Helps #115
> Replace syscall.Socketpair with net.Pipe

- acme.go
- dat.go
- disk_test.go
- ecmd.go
- elog.go
- exec.go
- file.go
- frame/box.go
- frame/box_test.go
- frame/insert_test.go
- frame/util.go
- frame/util_test.go
- fsys.go
- fsys_test.go
- look.go
- row_test.go
- text.go
- texter.go
- wind.go
These are the simple ones. There are more.
Common lints include:
* Not making use of type inference
* Underscore in identifier name
* Receiver name is not consistent
* Simplify `if` statements where the `else` part can be removed
* Use `foo++` instead of `foo += 1`; similarly for `foo--`
* Errors should not have a newline at the end
> Fix some golint warnings

- acme.go
- fsys.go
- signal_plan9.go
- signal_unix.go
- signal_windows.go
Plan9port and Plan 9 acme handles these signal:
```
char *oknotes[] ={
"delete",
"hangup",	// SIGHUP
"kill",		// SIGTERM
"exit",
nil
};
```
I'm not sure what generates the "delete" and "exit" signals, but SIGTERM
was missing from Edwood's list, so I've added that. SIGQUIT is useful
for debugging a Go program (typing ctrl-\ will print stack trace of all
running goroutines), so I removed that. SIGSTOP cannot be handled, so
that was also removed.
Edwood was ignoring all other signals, which seems wrong. I made it so
it'll only ignore what plan9port acme was ignoring:
```
char *ignotes[] = {
"sys: write on closed pipe",	// SIGPIPE
"sys: ttin",	// SIGTTIN
"sys: ttou",	// SIGTTOU
"sys: tstp",	// SIGTSTP
nil
};
```
Helps #115
Helps #116
> Make signal handling portable

- row.go
The resize problems only show up in Plan 9.
In plan9port, rect.Min.X is always 0.
Help #115
> Fix col resize issues when screen origin is not (0,0)

- col.go
The column blackness bug #52 is caused when `Window` objects are sized to 0 body lines (with an implied collapsing of the tag to 1 line of text.) Preventing sizing to 0 body lines prevents column blackness. So helps #52 but more work remains.
> Short term mitigation for column blackness #52

- col.go
The regression was introduced by #129.
We revert back to previous logic so that findWindowContainingY can't
return nil Window.
If you open a lot of windows in a short amount of time
(e.g. execute `B *.go` within edwood source directory),
`findWindowContainingY` seems to be returning a nil Window.
> Fix regression in findWindowContainingY

- col.go
- wind.go
Fix column blackness bug #52 in a way that correctly preserves tag
collapsing behaviour. Note that there appear to remain issues in the
implementation of Window.Resize that could do with additional
investigation.
> Fix column blackness

- col.go
- row.go
This is now consistent with p9p acme.
> Add trailing space to default row/col tag

- exec.go
- file.go
- wind.go
The `putseq` is a per-file concept but replicated in every window. Move
`putseq` into `File`
> Remove replicated window putseq

- dat.go
- ecmd.go
- fsys_test.go
- wind.go
- xfid.go
- This gets `Edit |cmd` and `Edit <cmd` working
- The Mutex wasn't even allocated because it was declared as a pointer
> Fix editout locking in file server and Edit command

- buf.go
- ecmd.go
- internal/regexp/README.md
- internal/regexp/backtrack.go
- internal/regexp/exec.go
- internal/regexp/onepass.go
- internal/regexp/regexp.go
- internal/regexp/runes.go
- internal/regexp/runes_test.go
- internal/regexp/runesb.go
- regx.go
- regx_test.go
- text.go
- texter.go
Edwood requires a regular expression implementation that works with
runes, correctly handles ^ and $ for selection, and enables backward
search. This commits adds an internal package `internal/regexp` that is
a copy of Go's regexp package but adds the methods Edwood needs (see the
README file in the package directory).
Also included are changes that make Edwood use the new regular
expression package. The Texter.View method is changed to return []rune
instead of []byte. This is harmless because this method was not being
used anywhere.
Fixes #157
> Reimplement regular expression

- acme.go
- addr.go
- ecmd.go
- edit.go
- exec.go
- file.go
- text.go
- wind.go
- xfid.go
* These were found by [staticcheck](https://staticcheck.io):
```
$ staticcheck -checks S1023,SA4011
acme.go:302:4: ineffective break statement. Did you mean to break out of the outer loop? (SA4011)
acme.go:444:2: redundant return statement (S1023)
acme.go:633:4: ineffective break statement. Did you mean to break out of the outer loop? (SA4011)
addr.go:99:3: redundant break statement (S1023)
addr.go:122:3: redundant break statement (S1023)
addr.go:249:4: ineffective break statement. Did you mean to break out of the outer loop? (SA4011)
addr.go:249:4: redundant break statement (S1023)
addr.go:268:4: ineffective break statement. Did you mean to break out of the outer loop? (SA4011)
addr.go:268:4: redundant break statement (S1023)
addr.go:305:4: ineffective break statement. Did you mean to …
```
> Remove redundant breaks and returns

- addr.go
- elog.go
- exec.go
- exec_test.go
- file.go
- fsys_test.go
- look.go
- row.go
- util.go
- wind.go
- xfid.go
```
$ staticcheck -checks 'S1*'
addr.go:16:2: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (S1008)
elog.go:90:23: should use make([]rune, len(r)) instead (S1019)
exec.go:419:7: should use strings.Contains(r, "/") instead (S1003)
exec_test.go:13:3: should use for range instead of for { select {} } (S1000)
file.go:96:9: should use bytes.Equal(h[:], h1[:]) instead (S1004)
fsys_test.go:413:6: should use strings.Contains(op, "focus") instead (S1003)
fsys_test.go:416:5: should use !strings.Contains(op, "new") instead (S1003)
look.go:85:6: should omit comparison to bool constant, can be simplified to !expanded (S1002)
look.go:185:5: should omit comparison to bool constant, can be simplified to !expanded (S1002)
look.go:758:6: should omit comparison to bool …
```
> Simplify some code (found by staticcheck)

- text.go
- text_test.go
Double clicking on the rune before the ending tag was returning bad selection:
```
Text.Select: DoubleClick returned 276, 0
panic: acme: textsetselect p0=262 p1=0 q0=276 q1=0 t.org=14 nchars=730
goroutine 66 [running, locked to thread]:
main.(*Text).SetSelect(0xc0002c0128, 0x114, 0x0)
/home/fhs/go/src/github.com/rjkroege/edwood/text.go:1320 +0x396
main.(*Text).Select(0xc0002c0128)
/home/fhs/go/src/github.com/rjkroege/edwood/text.go:1134 +0x7db
main.MovedMouse(0x351, 0x216, 0x1, 0x2220bd4b)
/home/fhs/go/src/github.com/rjkroege/edwood/acme.go:421 +0x47d
main.mousethread(0xc0000cc0c0)
/home/fhs/go/src/github.com/rjkroege/edwood/acme.go:300 +0x2bb
created by main.main
/home/fhs/go/src/github.com/rjkroege/edwood/acme.go:172 +0x968
```
> Fix crash when double clicking end of HTML text

- exec.go
- fsys.go
- fsys_test.go
- row.go
- text.go
The two bugs staticcheck found:
1. exec.go: Font command didn't parse arguments correctly
2. fsys.go: err shadowing bug in fsyswalk
```
$ staticcheck | grep -v U1000 | grep -v ST1012
exec.go:435:20: argument t is overwritten before first use (SA4009)
exec.go:695:22: argument t is overwritten before first use (SA4009)
exec.go:713:21: argument t is overwritten before first use (SA4009)
exec.go:762:22: argument t is overwritten before first use (SA4009)
exec.go:771:2: this value of r is never used (SA4006)
fsys.go:379:5: this value of err is never used (SA4006)
fsys.go:379:21: Errorf is a pure function but its return value is ignored (SA4017)
row.go:771:4: this value of l is never used (SA4006)
text.go:334:24: error strings should not be capitalized (ST1005)
```
> Fix some staticcheck warnings (including bugs)

- ecmd.go
- fsys.go
- fsys_test.go
- xfid.go
Renaming was done by gorename, so should be correct.
```
$ staticcheck -checks ST1012
fsys.go:52:2: error var Eperm should have name of the form ErrFoo (ST1012)
fsys.go:53:2: error var Eexist should have name of the form ErrFoo (ST1012)
fsys.go:54:2: error var Enotdir should have name of the form ErrFoo (ST1012)
xfid.go:19:5: error var Edel should have name of the form ErrFoo (ST1012)
xfid.go:20:5: error var Ebadctl should have name of the form ErrFoo (ST1012)
xfid.go:21:5: error var Ebadaddr should have name of the form ErrFoo (ST1012)
xfid.go:22:5: error var Eaddr should have name of the form ErrFoo (ST1012)
xfid.go:23:5: error var Einuse should have name of the form ErrFoo (ST1012)
xfid.go:24:5: error var Ebadevent should have name of the form ErrFoo (ST1012)
```
> Rename errors to conform to Go style

- .travis.yml
This is what the coverage report looks like: https://codecov.io/gh/fhs/edwood/branch/codecov
I'm not sure if you need to enable it at https://codecov.io/gh/rjkroege/edwood
> Send coverage report to codecov in Travis CI

- acme.go
- acme_test.go
- fsys.go
* Also gracefully terminate fsys reader
* Use Kill instead of Interrupt because Interrupt is not implemented on
Windows and it's what exec.CommandContext uses for cancellation.
> Terminate running commands when exiting

- dat.go
- exec.go
- look.go
- look_test.go
* Return *Expand instead of Expand
* Remove 2 fields from Expand
- bname was the same as name
(In the C code, it was the char* version of []rune name)
- ar is replaced with a local variable
* Remove special casing of C #include directive.
This is better handled by the plumber.
* Simplify and fix some logic
> Test and simplify expand

- addr.go
- ecmd.go
- edit.go
- exec.go
- internal/runes/runes.go
- internal/runes/runes_test.go
- look.go
- rune.go
- text.go
- util.go
Also use them:
gofmt -r 'runeeq -> runes.Equal' -w .
gofmt -r 'runestrchr -> runes.IndexRune' -w .
gofmt -r 'utfrune -> runes.IndexRune' -w .
gofmt -r 'runes.IndexRune(α, β) != -1 -> runes.ContainsRune(α, β)' -w .
gofmt -r 'runes.IndexRune(α, β) == -1 -> !runes.ContainsRune(α, β)' -w .
gofmt -r 'runes.ContainsRune([]rune(α), β) -> strings.ContainsRune(α, β)' -w .
gofmt -r 'runeEq -> runes.Equal' -w .
gofmt -r 'isIn -> runes.ContainsRune' -w .
> internal/runes: add IndexRune, ContainsRune and Equal

- file.go
- file_test.go
- text.go
The panic message gets printed when running tests, even after recover.
This gets rid of the minor annoyance.
> Change File.DelText to return error instead of panicking

- buf.go
- dat.go
- elog.go
- fsys.go
- text.go
- texter.go
- wind.go
- xfid.go
gofmt -r '(α(β)) -> α(β)' -w .
> Remove redundant parenthesis around function calls

- acme.go
- dat.go
- fsys.go
- text.go
- wind.go
- xfid.go
- Remove cputype/objtype because we have runtime.GOARCH/runtime.GOOS
- Move messagesize to fileServer struct
- Replace nullrect with image.ZR
> Remove some global variables

- acme.go
- buf.go
- col.go
- ecmd.go
- edit.go
- elog.go
- exec.go
- file.go
- internal/file/doc.go
- internal/file/file_hash.go
- look.go
- row.go
- scrl.go
- text.go
- util.go
- wind.go
- xfid.go
A bunch of cleanups aimed to isolate the internals of File.
> Reduce use of File's internal details

- text.go
- util.go
- util_test.go
Default error window name should be "+Error", not "/+Error". This
allows access to files relative to the directory Edwood was launched in,
instead of relative to /.
Also append `\` instead of `/` to directories in Windows.
> Remove slash from default error window name

- README.md
- acme.go
- go.mod
- go.sum
- internal/draw/9fans.go
- internal/draw/duitdraw.go
Duitdraw in macOS require special handling so that things run on the
same thread as `main.main`. See
https://github.com/ktye/duitdraw/issues/12
Based on my testing, duitdraw on macOS is more buggy than X11 and
Windows, but this at least gets Edwood in a usable state. It often
segfaults when you resize Edwood.
> Get duitdraw working in macOS

- acme.go
- exec.go
- fsys_test.go
- internal/dumpfile/parse.go
- internal/dumpfile/parse_test.go
- look.go
- row.go
- row_test.go
- testdata/empty-two-cols.dump
- testdata/example.dump
- testdata/multi-line-tag.dump
* Create internal/dumpfile package which uses JSON to store dump data.
This breaks compatiblity with acme. However, this will make it
easier to extend the dump file, storing more data, adding support
for things like multi-line tags. There is a proposed solution to
add multi-line tags in acme which uses hacks like using unicode PUA:
https://github.com/9fans/plan9port/pull/153
* We can now save and load multi-line tags
* Fix loading dump file with no windows (see #206)
* Remove temporary file containing window body after loading Unsaved
window
* Move LoadFont into internal/dumpfile package
* Remove lookid (commened out C code) because it's already been
implemented as Row.LookupWin.
Fixes #206
> Change dump file format to use JSON

- file.go
- fsys.go
- row.go
- row_test.go
- wind.go
* Replace File.dumpid with a local variable. Also, fix how dumpid
initialization depends on the order of windows: we were setting dumpid
for an external window to -1, and then resetting it back to 0 for a
zerox of that window.
* Window.dumpid was not being used. It's used in acme to find the
original window that's zeroxed, but Edwood searches by filename instead.
> Remove dumpid field from File and Window

- text.go
- text_test.go
The warning looked like this when listing /some/dir:
can't stat foo: stat /some/dir/foo: no such file or directory
> Remove broken symlink warning on directory listing

- row_test.go
- wind.go
When operating on a retina display, 9fans draw.Font prefixes font
names with its scale factor. Dump files are font resolution
independent so ignore the scale factor when validating Dump/Load
configuration.
> Fix new JSON dump test on retina displays

- exec.go
- exec_test.go
- file.go
- text.go
SameFile will make use of Qid in [Plan 9](https://golang.org/src/os/types_plan9.go) and inode in [unix](https://golang.org/src/os/types_unix.go) systems (same as plan9port).
> Replace qidpath with os.FileInfo and call to os.SameFile

- acme.go
- dat.go
- exec.go
- file.go
- file_test.go
- text.go
* Remove `Unimpl` because everything has been implemented!
* Three places where `Untested` was use:
- `waitthread`: removed `libthread` related code we should never reach
- `checkhash`: added a test
- `run`: already tested mostly via `runproc`
* Code coverage report is a better alternative to `Untested`.
* Removed other prints that are too noisy.
> Remove Unimpl, Untested, and other debugging prints

- acme.go
- fsys_p9p.go
When Edwood closes connection to the file server before exit, wait for
`9pserve` can return this error:
9pserve wait failed: waitid: no child processes.
It's important that we don't panic for this error, so that Edwood has a
chance to finish cleaning up before exit. In particular, if Edwood is in
the middle of writing to the dump file, the dump file may end up being
truncated to an empty file.
We also move `killprocs` to *after* `row.Dump`. This leads to a dump
file more consistent with the `Dump` command. It ensures that all the
external commands currently running show up in the row tag inside the
dump file, even if its undesirable (at least to me).
Also, do not write to dump file on `Exit` command. We only write to dump
file on unexpected signals (SIGINT, SIGTERM, etc.). This behavior …
> Fix race when saving to dump file before exit

- acme.go
- edit_test.go
- elog.go
- row.go
Warn instead of panic when running a sequence of sam commands in the
elog that are out of order. Fixes #177. Also add a test of the sam b
command.
> Don't panic on out-of order sam commands.

- edit_test.go
- rowmock_test.go
The sam command tests needed a mock of the Edwood row/column/window
model. Refactor this somewhat adhoc code into a general framework
based on creating a test mock from Edwood intermediate dumpfile
format.
> Introduce a general row/column/window mock

- text.go
- text_test.go
This may not fix the underlying issue but it at least prevents the crash
and prints a debugging message for further investigation.
Fixes #244
> Fix crash due to negative slice length in Text.fill

- dat.go
- xfid.go
The closed window is the one associated with mousetext. Lock row while
mousetext is set to nil (due to window close), which prevents
mousethread from attempting to lock the closed window.
Fixes #235
> Fix crash while attempting to lock a closed window in mousethread

- .travis.yml
- fsys_windows.go
- internal/frame/util.go
Fix these two `staticcheck` warnings:
```
fsys_windows.go:21:20: error strings should not be capitalized (ST1005)
internal\frame\util.go:131:4: this value of b is never used (SA4006)
```
We ignore these two checks because there are failure cases that I'm not
sure is worth fixing:
```
$ staticcheck -explain U1000
Unused code
$ staticcheck -explain SA4003
Comparing unsigned values against negative values is pointless
```
> .travis.yml: run staticcheck and misspell

- addr.go
- addr_test.go
- xfid.go
- xfid_test.go
The fix is in `acmeregexp`, where we now return `sel[0]`
only if `len(sel) != 0`.
Fixes #258
> Fix crash on failed regular expression search from file server

- ecmd.go
- edit_test.go
- exec.go
- look.go
- look_test.go
- text.go
- text_test.go
- util.go
- util_test.go
- wind.go
* When plumbing from the row tag, we were sending "" as the `Dir` in the
`plumb.Message`. We now send the absolute path to current working
directory instead.
* Remove `dirname` function, which had the same functionality as
`Text.DirName`.
* Change `Text.DirName` to always return a cleaned path (as returned by
`filepath.Clean`). This means we'll never return "", which becomes "."
after clean.
* Removed some hacks (marked with "sigh") where "." was being converted
to "" for some unknown reason. As far as I can see, this hack isn't
necessary in Go. When "." is used in `filepath.Join` and `exec.Cmd.Dir`,
it works as expected.
> Test Text.DirName and fix plumbing from row tag

- acme.go
- acme_test.go
- dat.go
- exec.go
- fsys.go
- fsys_plan9.go
- look.go
- row.go
- text_test.go
- util.go
- wind.go
This flag will enable us to see Go runtime profiles from a HTTP server
(see https://golang.org/pkg/net/http/pprof/). When Edwood is misbehaving
but haven't crashed, it'll be useful for getting a stacktrace of all
running goroutines, run `pprof`, etc.
Also, fix `-r` flag (flag value wasn't being used),
and remove some flag related global variables.
> Add -debug flag for debugging using net/http/pprof

- internal/edwoodtest/draw.go
- internal/ninep/util.go
- internal/ninep/util_test.go
- row_test.go
- testdata/example.dump
- testdata/example.index
- testdata/hello.go
- testdata/multi-line-tag.dump
- testdata/multi-line-tag.index
- xfid.go
- xfid_test.go
* The helper functions are similar to readbuf(3) and readstr(3) in lib9p.
* Remove TODO about not respecting utf8 boundaries for read requests as
it's generally the client's responsibility to make sure full runes are
read.
* Only include the first line of a multi-line tag for index file.
* Adjust test dump files to only use files within the testdata directory.
> Add helper functions to fill in Fcall.Data and Fcall.Count for read requests

- buf.go
- wind.go
- xfid.go
- xfid_test.go
* Fix crash due to Window.ctrllock not being initialized.
* Disable `unlock` and `lock` ctl messages because they can crash or hang Edwood.
* Fix `del` ctl message.
> Test xfidopen, xfidclose and xfidwrite

- acme.go
- wind.go
- xfid.go
- xfid_test.go
* Always send error response to 9P client for invalid QID (instead of
showing a warning to user).
* Clean up xfidallocthread goroutine after test as having it running in
the background can interfere with other tests.
> Test xfidread, xfidflush and xfidctl

- dat.go
- fsys.go
- fsys_test.go
* Don't panic if Tattach Aname is not an integer
(e.g. `9p -A foo acme ls` was crashing Edwood).
* Respond with Rerror if Tattach Aname is invalid, instead of succeeding
but showing a warning to user. Edwood will take care of showing the
warning when it's the client (in `exec.go:/runproc`).
* Change type of DirTab.perm from uint to plan9.Perm.
> Add more file server tests (mainly Tversion, Tattach, Tstat, and Topen)

- fsys.go
- fsys_test.go
- internal/ninep/util.go
- internal/ninep/util_test.go
* Fix crash if read buffer is not large enough to fit a directory entry.
* Added a helper function similar to lib9p's dirread9p(3).
* Don't send partial directory entry for Tstat.
> Refactor and test directory read in file server

- xfid.go
- xfid_test.go
* Fixes #272
* Stop processing input on error "file dirty". This behavior now matches
acme.
* Also stop processing on error "bad character in file name". This
behavior does not match acme but I don't see why we should make use of a
bad window name, and then continue processing more input (which can
overwrite the error).
* Simplify how we compute the number bytes that were processed
(`Fcall.Count` in response). Generally, we always process the full
buffer if we don't encounter an error. For error, we send a `Rerror`
response, which has no count.
> Fix crash when writing muti-line commands containing deletion to ctl file

- .travis.yml
- acme.go
- acme_test.go
- dat.go
- exec_test.go
* Prevent cycle in command linked list (Fixes #279)
* Change command linked list to a slice
* Change waitthread's pids from a linked list to a map
* Add more waitthread test
* Set `GOPROXY` environment variable in Travis (attempt to fix `go get` timeouts)
> Fix waitthread infinite loop trying to find PID in command list

- .travis.yml
- acme.go
- col.go
- exec.go
- internal/frame/draw.go
- internal/frame/select.go
- internal/frame/tick.go
- row.go
- scrl.go
- text.go
- wind.go
Also, remove use of deprecated `image.ZP` and `image.ZR`. Go 1.13 has deprecated these variables in favor of struct literals. Staticcheck complains if we use them. Changes made with:
```
gofmt -w -r 'image.ZP -> image.Point{}' .
gofmt -w -r 'image.ZR -> image.Rectangle{}' .
```
> .travis.yml: drop Go 1.11.x and add Go 1.13.x

- acme.go
- fsys.go
- fsys_test.go
- fsys_windows.go
* Allow `Uname` mismatch in `Tattach`, since we don't have any authentication and some libraries (e.g. `9fans.net/go/plan9/client`) gets `Uname` wrong anyway.
* Add `-fsys.addr` flag for Windows. This allows user to listen to a specified port instead of a random one.
* Replace `$HOME` with `os.UserHomeDir()`, which was introduced in Go 1.12. Update #222
Helps https://github.com/fhs/acme-lsp/issues/14
> Fix some Windows issues

- exec.go
- internal/edwoodtest/draw.go
- xfid.go
- xfid_test.go
This fixes Send command crashing Edwood, Edit command generating wrong
event, and possibly other issues caused by having window owner set to 0
while having a lock on it.
Window owner was being set to 0 following Unlock, Lock sequence.
Since Unlock sets owner to 0, we need to avoid using w.owner after
calling Unlock.
Fixes #284
Fixes #285
> Fix incorrect window owner on writes to event file

- acme.go
- ecmd.go
- ecmd_test.go
- edit_test.go
- exec.go
- fsys_test.go
- fsys_windows.go
- internal/frame/util.go
- internal/regexp/onepass.go
- util.go
This is just a copy of the fix applied to p9p acme:
https://github.com/9fans/plan9port/commit/d2df5d6cbd345e101732fe7d22bb5b3baa5fb61a
Fixes #291
> Fix crash in 'Edit X |cat' with multiple windows

- edit_test.go
- look.go
- text.go
- text_test.go
- wind.go
- wind_test.go
This is based on the following p9p acme change:
$ git log --oneline d2df5d..573169d src/cmd/acme
573169dd acme: fix buffer overflow introduced in parsetag refactor
86bfd607 acme: fix movetodel for spaces in file names
7b1c85f6 acme: allow spaces in window names
6bddb06b acme: one more place to use parsetag
81d992e3 acme: factor out tag parsing code
Notably https://github.com/9fans/plan9port/commit/7b1c85f6e8031a50e8e6f5977d12bea820e921ca
Fixes #292
> Add support for filenames with spaces

- xfid.go
- xfid_test.go
The "font" ctl message accepts an absolute path to a font. If the font
exists, the window will use the given font.
This control message exists in acme:
https://github.com/9fans/plan9port/blob/master/src/cmd/acme/xfid.c#L704-L721
> edwood: implement "font" ctl message to change font

- look.go
- look_test.go
Go mode makes directory names with `@` signs in them. E.g.
/Users/rjkroege/tools/gopkg/pkg/mod/github.com/fhs/mux9p@v0.2.0/mux9p.go.
Permit Edwood to open these files per #306.
> Support paths into gomod directories.

- text.go
After typing text in Acme, one can press ESC to select the previously typed text and press ESC again to delete it. This is possible because `eq0` [is set when typing begins](https://github.com/9fans/plan9port/blob/70cc6e5ba7798b315c3fb3aae19620a01604a459/src/cmd/acme/text.c#L910) and is checked for [when ESC is pressed](https://github.com/9fans/plan9port/blob/70cc6e5ba7798b315c3fb3aae19620a01604a459/src/cmd/acme/text.c#L836). This PR adds support for this feature by setting `eq0` to the first address (0) when text is typed in a similar manner as is done in Acme.
> Handle ESC like Acme

- file.go
Currently Undo is broken for disk filenames, a temporary fix wouldn't be worth it as it would need to be fixed again following the new undo structure, added a TODO for when that is ready.  #334
> Added TODO in File to fix undo for disk filenames 

- ecmd.go
- edit_test.go
- internal/elog/elog.go
- observable_editable_buffer.go
Tests expect there to be a newline between errors which wasn't present due to a fix for staticcheck.
> Added newline to first error when multiple are returned from elog

- col.go
- fsys.go
- fsys_plan9.go
- fsys_unix.go
- fsys_windows.go
- look.go
- observable_editable_buffer.go
- row.go
- text.go
- util.go
- wind.go
- xfid.go
Fixed imports that were previously not following convention by being mixed in with go language imports.
> Moved external imports to the bottom of the imports.

- acme.go
- col.go
- ecmd.go
- exec.go
- exec_test.go
- file/file.go
- look.go
- row.go
- scrl.go
- text.go
- wind.go
Changed all callers of file.Size() to file.Nr() as size will soon be in bytes and currently the size is in runes. Closes: "TODO(rjk): Switch all callers to Nr() as would be the number of bytes when backed by undo.RuneArray." #334
> Changed all callers of file.Size() to file.Nr()

- acme.go
- acme_debug.go
- acme_nodebug.go
```
; go build -tags debug
; ls -l edwood
-rwxr-xr-x 1 fhs fhs 8941213 Sep  4 12:05 edwood
; go build
; ls -l edwood
-rwxr-xr-x 1 fhs fhs 5098257 Sep  4 12:06 edwood
```
> Reduce binary size by hiding profiler under a build tag

- acme_test.go
- dat.go
- ecmd_test.go
- exec_test.go
- fsys_plan9.go
- look_test.go
- rowmock_test.go
- util_test.go
- xfid_test.go
plan9.MREPL was only used once, but that usage
broke plan9 compilation.
While we're at it, run goimports.
Fixes plan9 builds.
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
> fs_plan9.go: plan9.MREPL -> MREPL

- file/bytes.go
- file/undo.go
- file/undo_test.go
This reverts commit f82a8ea5 as it's no longer needed for the direction that undo.Buffer is going in.
> Revert "Use nested file.Bytes"

- file/file.go
- file/observable_editable_buffer.go
- file/rune_array.go
- regx.go
- sam/texter.go
- text.go
- text_test.go
- wind.go
Simplify the `ObservableEditableBuffer` API surface to reduce the work
needed in forthcoming CLs to adapte OEB to `file.Buffer`.
> OEB Simplifications

- file/file.go
- file/file_test.go
- file/observable_editable_buffer.go
Pull seq up out of file.Fiel into file.ObservableEditableBuffer. This
helps with #97 by reducing the work needed to implement
ObservableEditableBuffer functions in terms of file.Buffer functions.
> Pull seq up out of file

- wind.go
My recent change #371 broke tag reconstruction. Oops. Fix that.
> Fix no-typing-in-tags bug

- col.go
- rowmock_test.go
- text.go
- text_test.go
- wind.go
Previous fix b859964fa27ed22a5c9fc81b5c46e467ed611a8c for bug that I
introduced in #371 failed to correctly handle text insertion in all
parts of the tag. Fix it more comprehensively. Also improve fidelity
of some tests by building a better model for tab insertion tests.
> Better tag typing fix

- exec.go
- exec_test.go
- globals.go
- text.go
exec.go contains functions for most of the built-in commands
recognized by Edwood. Document the format and calling conventions for
these functions more precisely before writing additional unit tests
for them.
> Improved documentation for exec functions

- .github/workflows/edwood.yml
- acme_debug.go
- acme_nodebug.go
- acme_p9p.go
- acme_plan9.go
- acme_unix.go
- acme_windows.go
- draw/9fans.go
- draw/duitdraw.go
- dumpfile/legacy_parse_cases_test.go
- fsys_p9p.go
- fsys_unix.go
- look_posix.go
We can use a newer Go than 1.14. Support current and last version.
> Update the Go version used in the CI

- edit_test.go
- exec.go
- exec_test.go
- file/file.go
- file/observable_editable_buffer.go
- row.go
- row_test.go
- rowmock_test.go
Partially address #383 by adding a more comprehensive row, col, wind, text, oeb test fixture and demonstrate that Undo/Redo history sequences correctly diverge and rejoin across a pair of different Window instances.
> Add test for multi-window Undo/Redo

- row_test.go
- wind.go
TestRowLoad is fragile to pathing differences between the local
directory and test data when the local directory paths are shorter (in
runes). Fix this and a few other issues seen along the way.
> Improved TestRowLoad tolerance for alternate pathing

- filename_undo_test.go
There are complicated interactions between filename changes and Undo.
Show that Undo works properly on filename modifications. Note that the
tests demonstrate a pre-existing failure with the updating of the tag
selection after Undo.
> Test Undo of filename changes

- exec.go
Build a new environment using the existing environment and add the
winid, acmeaddr, %, and samfile variable to that.
> Don't pollute edwood's environment when calling out.

- exec_test.go
- file/file.go
- file/file_test.go
- file/observable_editable_buffer.go
- file/tag_status_observer.go
- filename_undo_test.go
- look.go
- row.go
- row_test.go
- rowmock_test.go
- wind.go
- wind_test.go
- xfid_test.go
Use an observer scheme to invoke `Window.setTag` instead of the manual
calls to `Window.SetTag`. This significantly reduces the number of
calls to `SetTag`: e.g. in editing this commit message, we reduced the
number of `setTag` invocations by ~99%.
This change also contributes to #400 by setting up the start of an
observer structure for plumbing together Undo actions *in the tag*
into filename changes.
> Observer-driven tag updates

- tagindex.go
- text.go
- text_test.go
- wind.go
- wind_test.go
- xfid_test.go
ParseTag is comparably expensive: reading the entire tag contents and
applying multiple string matches against it. Reduce invocations of
ParseTag by virtue of making Window an observer on the tag's
file.ObservableEditableBuffer. Helps with #400.
> Reduce invocations of ParseTag

- exec.go
- exec_test.go
- file/file_test.go
- file/observable_editable_buffer.go
- wind.go
My change to introduce observer-driven tag updates failed to correctly
propagate tag updates after doing a Put operation. Corrected this.
Helps eventually with #400.
> Fix bug in observer-driven tag updates

- filename_undo_test.go
- tagindex.go
- testdata/example.dump
Improve the updating of the selection in Window tags across various
actions (e.g. Undo of a file name change) where Edwood
programmatically updates the contents of the tag. Fixes #400.
> More sensibly update tag selections

- file/file.go
- file/observable_editable_buffer.go
- file/rune_array.go
- text.go
- wind.go
- xfid.go
Further simplify the ObservableEditableBuffer interface. This will
(slightly) reduce the work needed to complete #97. And seemed like a
nice cleanup. Also updated a number of comments to better specify API
surfaces.
> Remove ObservableEditableBuffer.Reset()

- file/file.go
- file/observable_editable_buffer.go
- file/tag_status_observer.go
- wind.go
Remove some unnecessary code added as part of fixing #400. Makes
TagStatusObserver simpler.
> Simplify TagStatusObserver

- regexp/runesb.go
- regexp/searchspeed_test.go
Reverse search in Edwood is much slower than forward search. From a
benchmark added in this CL:
BenchmarkFindForward-10     	   89755	     11822 ns/op
BenchmarkFindBackward-10    	    1228	    987333 ns/op
This is because reverse search ended up running in O(n^2) time instead
of O(n). Improve reverse search by re-expressing it in terms of
forward search. This fixes #301.
> Make reverse search faster

- addr.go
- ecmd_test.go
- exec_test.go
- guide
- rowmock_test.go
- text.go
slower than `x`. Add a benchmark BenchmarkLargeEditTargets.* to
compare the performance of equivalent `s` and `x` edits on a range of
buffer sizes.
> s_cmd vs x_cmd benchmark

- edwoodtest/colornames.go
- edwoodtest/draw.go
- frame/frame.go
- frame/guide
- frame/insert_test.go
- guide
- row_test.go
- rowmock_test.go
- wind_test.go
- xfid_test.go
To help with #56 and other frame.Frame improvements, update the draw
mock to record the commands sent to 9fans.net/go/draw. Further use
this in some simple tests of frame.Insert to demonstrate that the
mocks work and significantly expand test coverage of the frame unit
tests.
> Enhanced framework for frame.Frame tests

- edwoodtest/draw.go
- frame/insert.go
- frame/insert_test.go
Ongoing preparatory work to address issue #56: improve the frame test
harness, simplify the edwoodtest mock display code's output (to make
it easier to reason about) and expand test coverage on frame.Insert.
> Increased frame test coverage

- xfid.go
Fixes #57: we lookup a window in `edwood/util.go:66`. It's happy to
find a window from `g.row` while `g.row` is locked and that window
struct can be invalid at the time during a `del()` action. So lock the
row/column struct while obtaining the window object.
> Fix a race condition with error windows

- file/file_test.go
- file/offset_tuple.go
- file/undo.go
- file/undo_test.go
The original undo.Buffer implementation provided only
byte-grannularity access. Edwood assumes the ability to access its
backing text storage at rune boundaries. Add support for (hopefully)
efficient rune-boundary access.
> Rune-boundary access to undo.Buffer

- file/buffer_adapter.go
- file/file.go
- file/file_file_test.go
- file/file_test.go
- file/helpers_test.go
- file/observable_editable_buffer.go
Prior to installing file.Buffer underneath ObservableEditableBuffer,
insert an interposing interface layer BufferAdapter to permit an OEB
to use either a file.File or a file.Buffer.
> Hoist ObservableEditableBuffer

- file/file_test.go
- file/observable_editable_buffer.go
SaveableAndDirty only needs to be true for buffers with Undo so
there's no need to invoke HasUncommitedChanges. Helps with #97 because
file.Buffer does not have a Commit concept.
> Remove HasUncommitedChanges from SaveableAndDirty

- file/buffer_adapter.go
- file/file.go
- file/file_test.go
- file/helpers_test.go
- file/observable_editable_buffer.go
- file/undo.go
- file/undo_test.go
- text.go
Previous changes have added a newer alternative to file.File:
file.Buffer that provides a more efficient backing storage mechanism
for textual data with undo. This CL adds an adapter that implements
ObservableEditableBuffer in terms of file.Buffer. Noteworthy changes:
* supporting the oeb callback logic for Undo/Reo from file.Buffer
* track the bounds of Undo/Redo action
* track undoable file name changes in file.Buffer
* relocate oeb callbacks where possible to do so
* modify oeb tests to invoke both the file.File and file.Buffer
implementations
Provides the core of #97 -- a more idiomatic text buffer
implementation.
> Implement OEB in terms of file.Buffer

- file/buffer_adapter.go
- file/buffer_adapter_test.go
- file/undo.go
- file/undo_test.go
With this change, Edwood can successfully do interactive editing
operations when using the newtype buffers. (Run with --newtypebuffer).
Helps with #97.
> Basic interactive editing with newtype buffers

- file/buffer.go
- file/buffer_adapter.go
- file/helpers_test.go
- file/observable_editable_buffer.go
While implementing the newtype file.Buffer, I'd abstracted it
internally to exist both old and new types to exist simultaneously.
With the removal of old type buffers, remove this. Cleanup that's part
of #97.
> De-hoisted the oeb implementation

- frame/frame.go
- frame/insert.go
- frame/insert_test.go
- frame/unlockedproxy.go
- framemock_test.go
frame promptly converts its input []rune into []byte. This is
unnecessary when file.Buffer stores and can provide inserts as []byte.
Modify frame to provide []byte insertion.
> Add []byte Insert to frame

- exec.go
Environment variables like`$samfile`, `$%`, and `$winid` were not being set when the command was being executed using `Hard()` (acmeshell not set, command contains `$`, etc). For example, in acme you can execute `echo $winid` and see the window id printed in an error window which can be useful in many situations. This PR restores restores that original acme behavior in Edwood.
Adding tests for these cases requires that the `Window` is available to `runproc` which the current test suite does not set. Let me know if there is somewhere else this should be tested and I can add test cases for this.
> Set environment for shell cmd execution

- file/buffer.go
- file/buffer_adapter.go
- file/buffer_adapter_test.go
- file/buffer_observer.go
- file/helpers_test.go
- file/observable_editable_buffer.go
- file/offset_tuple.go
- frame/insert.go
- tagindex.go
- text.go
- wind.go
Change the file.BufferObserver interface to eliminate all unnecessary
[]byte-[]rune conversions down into frame.
> no-conversion observer to frame

- file/buffer.go
- file/buffer_adapter.go
- file/buffer_adapter_test.go
- file/buffer_test.go
- file/file_test.go
- file/observable_editable_buffer.go
- file/offset_tuple.go
- look_test.go
My pragmatic (aka lazy) implementation of the code connecting newtype
file.Buffer to ObservableEditableBuffer "improved" ReadC from O(n) to
O(n^2). This reduced performance. I fixed this:
* Introduce a benchmark to clearly demonstrate the magnitude of my
foolishness.
* Introduce an optimized RuneTuple that used a cached location to
speed up incremental RuneTuple operations. In partciular, O(1) to move
forward or backwards character-by-character.
* Modify findPiece to offer a similar optimization (and run in O(1) if
following a RuneTuple operation.)
* Cache the Nr() computation to reduce the runtime of loops in Edwood
that call Nr() in the loop
* Write a new implementation of ReadC using all of this.
Performance benefit:
Before: BenchmarkLook3/jumpToNumberedLine-10         	       1 …
> Efficient ReadC

- file/buffer.go
- file/buffer_test.go
- file/offset_tuple.go
- text.go
- wind.go
Cache both the number of runes and number of bytes in a file.Buffer
for efficiently obtaining an OffsetTuple for the end of the Buffer.
> Add buffer.End()

- acme.go
- exec.go
Fix #331: correctly snarf and paste large buffers.
> Correctly support large snarf buffers

- frame/boxtest_helpers_test.go
- frame/insert.go
- frame/insert_test.go
This fixes #438: The default case in `bxscan` was not ignoring tabs that had already been placed into a box in the associated switch statement case, leading to `frbox.Ptr` not containing the last character when this occurred. As an example, `frbox.Ptr` was being built up as follows:
```
[9]
[9 120]
[9 120 102]
[9 120 102 105]
[9 120 102 105 100]
[9 120 102 105 100 95]
[9 120 102 105 100 95 116]
[9 120 102 105 100 95 116 101]
[9 120 102 105 100 95 116 101 115]
[9 120 102 105 100 95 116 101 115 116]
[9 120 102 105 100 95 116 101 115 116 46]
[9 120 102 105 100 95 116 101 115 116 46 103]
```
Changing the default case to only take a slice of `inby` from the current index fixes this issue:
```
[120]
[120 102]
[120 102 105]
[120 102 105 100]
[120 102 105 100 95]
[120 102 105 100 95 116]
[120 102 …
```
> Fix bxscan default insert

- acme.go
- edwoodtest/draw.go
- fsys_test.go
- guide
- row_test.go
- wind.go
- xfid_test.go
The Fsys tests launch an Edwood instance and then connect to it via
the 9p protocol. Previously this Edwood instance required a real
display, devdraw, window server, etc. This CL modifies the startup
logic to let this Edwood instance instead use a mock Display
instance.
> Use a mock Display instance in Fsys testing

- file/buffer_adapter.go
- file/file_test.go
- file/observable_editable_buffer.go
- text.go
- text_test.go
Now that newtype text buffers don't require Commit, further cleanup
the code around this.
> Additional removal of Commit concept

- frame/boxtest_helpers_test.go
- frame/draw.go
- frame/frame.go
- frame/insert.go
- frame/insert_more_test.go
- frame/insert_test.go
- frame/ptofchar.go
- frame/util.go
Inserting an actual newline at the end of a soft line-broken box no
longer inserts a spurious blank line. This fixes a pernicious
rendering issue.
> Fix a rendering bug with filled lines

- text.go
Fix a persistent niggle in the UI: pressing backspace when there's a
non-zero selection, merely delete the selection and don't delete the
additional character.
> Don't backspace if there's a selection

- exec.go
- file/observable_editable_buffer.go
- guide
- look.go
- look_test.go
- tagindex.go
- tagindex_test.go
- testdata/example.index
- testdata/multi-line-tag.index
- text.go
- text_test.go
- wind_test.go
Get on a directory now wraps filenames with spaces with single quotes.
Tag of a file with a space in the name now has the filename surrounded by single quotes.
Look now tries to find a file between single quotes, and correctly extends to an address suffix: 'a b':/foo
> Spaces in names

- expandfile.go
- expandfile_win.go
- look.go
- regexp/runes.go
- regexp/runes_test.go
Add windows-specific handling of filename Looks.
Uses regexp to find both filenames and quoted filenames followed by addresses.
Simplifies the code dramatically, at the cost of likely (minimal) overhead, and trades
comprehension of all the per-character parsing with regexp understanding.
> Windows filename handling

- expandfile_win.go
Windows filenames are very permissive.  For Look we want to use a better heuristic than "longest".  So this cl changes to delimit filenames by multiple whitespaces in row.  If you have two spaces in your filename you can sweep it out.
> Delimit filenames by multiple spaces

- exec.go
> Correct return parameter order; fix rune counts

- expandfile_win.go
Was broken in the Tag where the various trailing words would confuse it into expanding too long a filename.
Fixed by peeling off trailing words and testing for being a valid file.
Also correct a bug where some filename substrings did not include the clicked position.
> Fix expandfile windows

- xfid.go
This change fixes #499: nomark works correctly when setting the name
of a buffer.
> Fix error in xfid undo handling

- text.go
On windows, ctrl-{z,x,c,v} are shortcuts for undo, cut, copy, paste.
Edwood did not implement this. Add these shortcuts.
> Add standard accelerators on Windows

- file/observable_editable_buffer.go
- xfid.go
When I refactored the undo code, I changed (perhaps wrongly) the
semantics of Undo marking. Adjust the filesystem interface to work
correctly despite this.
This is a better fix for #499.
> Fix a subtle bug with the mark API

- util.go
This patch fixes #482. Update the selection correctly when appending
warnings.
> Correctly update the selected region on appending errors.

- exec.go
- exec_test.go
- guide
Prepare for later bug fixes by starting to separate the code in
exec.go:/execute into more easily testable components.
> Fix 470: missing chords

- file/observable_editable_buffer.go
- wind.go
- xfid.go
- **Improved undo handling for filesystem mutations**
- **Implement Acme dirty semantics for filesystem changes**
> FS-originated modifications work the same as Acme

- .gitignore
- file/guide
- guide
I had a lot of cruft in my Edwood directory, test etc. Check it in,
delete it or hide it with .gitignore. Also update the guide file to
remove the C conversion tooling and add convenience links to my notes
tracking listing tests that I need to write.
> Cleanup Edwood Directory

- cmd/E/main.go
Because `plumb` takes paths with a positional suffix specifying the
location in the file, the name of the file in the event log is not
necessarily the same as the argument to plumb. Watch for ID values
from the log file instead of the argument to `plumb`.
> E doesn't correctly wait for files with different name patterns
